# Generated by Django 5.0.9 on 2024-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_grocerylist_grocerylistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='g_list',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
