# Generated by Django 5.1.3 on 2024-11-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surbub',
            new_name='suburb',
        ),
    ]
