# Generated by Django 5.0.9 on 2024-11-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
