# .github/workflows/main_shopwise.yml
name: Build, Test and Deploy Python app to Azure Web App

# Define when the workflow should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Check out repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python environment
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Create and activate virtual environment
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install project dependencies
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt


  deploy:
    needs: build_and_test # Wait for build_and_test job
    # Don't deploy on PRs
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download build artifacts
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Prepare for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "shopwise"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CEA5E268CBE34E80A9A22CA03E19D129 }}
